baseURL = "/"
languageCode = "ja"
title = "Massas's Football Mamager 2023 Data"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  googleAnalyticsID = "G-R0JB4VHB5E"
